services:
  postgres:
    container_name: postgres
    image: postgres:14.8-alpine3.18
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: on-failure

  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./certs:/app/certs
    depends_on:
      - postgres
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Открываем 80 порт для Nginx
    volumes:
      - ./static:/var/www/static  # Монтируем статику в Nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Монтируем конфиг Nginx
    depends_on:
      - backend
    restart: unless-stopped