import operator
from operator import itemgetter

from aiogram_dialog import Dialog, Window
from aiogram_dialog.widgets.input import TextInput
from aiogram_dialog.widgets.kbd import (
    Back,
    Button,
    Calendar,
    Group,
    Select,
    ScrollingGroup,
    SwitchTo,
)
from aiogram_dialog.widgets.text import Format

from core.config import settings
from . import getters
from . import handlers
from .states import CreateTaskStates, TasksManagementStates
from routers.common.handlers import (
    back_to_creation_selection,
    is_short_text,
    on_incorrect_text,
    save_text_by_key,
    back_to_view_selection,
)
from routers.common.getters import (
    edit_name,
)
from .repository import repository

create_task_dialog = Dialog(
    Window(
        Format(text="{task_name}"),
        Button(
            text=Format("{back}"),
            id="back_to_creation_selection",
            on_click=back_to_creation_selection,
        ),
        TextInput(
            id="task_name_input",
            type_factory=is_short_text(
                max_length=settings.bot.max_name_length,
            ),
            on_success=save_text_by_key(key="name"),
            on_error=on_incorrect_text,
        ),
        getter=getters.task_name,
        state=CreateTaskStates.name,
    ),
    Window(
        Format(text="{task_description}"),
        Back(text=Format(text="{back}")),
        TextInput(
            id="task_description_input",
            type_factory=is_short_text(
                max_length=settings.bot.max_description_length,
            ),
            on_success=save_text_by_key(key="description"),
            on_error=on_incorrect_text,
        ),
        getter=getters.task_description,
        state=CreateTaskStates.description,
    ),
    Window(
        Format(text="{calendar}"),
        Calendar(id="calendar", on_click=handlers.on_date_selected),
        Back(text=Format(text="{back}")),
        getter=getters.task_date,
        state=CreateTaskStates.date,
    ),
    Window(
        Format(text="{hour_text}"),
        Group(
            Select(
                Format("{item[0]}"),
                id="hour",
                item_id_getter=itemgetter(1),
                items="hours",
                on_click=handlers.save_hour,
            ),
            width=2,
        ),
        Back(text=Format(text="{back}")),
        getter=getters.task_hour,
        state=CreateTaskStates.hour,
    ),
    Window(
        Format(text="{notification_hour_text}"),
        Group(
            Select(
                Format("{item[0]}"),
                id="hour",
                item_id_getter=itemgetter(1),
                items="hours",
                on_click=handlers.save_task,
            ),
            width=2,
        ),
        Back(text=Format(text="{back}")),
        getter=getters.task_notification_hour,
        state=CreateTaskStates.notification_hour,
    ),
)


tasks_management_dialog = Dialog(
    Window(
        Format(text="{items_text}"),
        ScrollingGroup(
            Select(
                Format("{item[0]}"),
                id="tasks",
                item_id_getter=operator.itemgetter(1),
                items="items",
                on_click=repository.on_click_item,
            ),
            id="all_tasks",
            width=1,
            height=5,
        ),
        Button(
            Format(text="{load_more}"),
            id="load_tasks",
            when="can_be_loaded",
            on_click=repository.upload_more_items,
        ),
        Button(
            Format(text="{back}"),
            id="back_to_view_selection",
            on_click=back_to_view_selection,
        ),
        state=TasksManagementStates.view_all,
        getter=repository.get_user_resources,
    ),
    Window(
        Format(text="{item_text}"),
        SwitchTo(
            text=Format(text="{edit_text}"),
            id="edit_task",
            state=TasksManagementStates.edit,
        ),
        SwitchTo(
            text=Format(text="{delete_text}"),
            id="delete_task",
            state=TasksManagementStates.delete,
        ),
        Back(text=Format(text="{back}")),
        state=TasksManagementStates.view_details,
        getter=repository.get_item_details,
    ),
    Window(
        Format(text="{confirm_text}"),
        Button(
            text=Format(text="{confirm_delete_task_text}"),
            id="confirm_delete_task",
            on_click=repository.delete_item,
        ),
        SwitchTo(
            text=Format(text="{back}"),
            id="cancel_task_deletion",
            state=TasksManagementStates.view_details,
        ),
        state=TasksManagementStates.delete,
        getter=getters.delete_task,
    ),
    Window(
        Format(text="{task_text}"),
        SwitchTo(
            text=Format(text="{name}"),
            id="change_name",
            state=TasksManagementStates.edit_name,
        ),
        SwitchTo(
            text=Format(text="{description_text}"),
            id="change_description",
            state=TasksManagementStates.edit_description,
        ),
        SwitchTo(
            text=Format(text="{deadline_date_text}"),
            id="change_deadline_date",
            state=TasksManagementStates.edit_deadline_date,
        ),
        SwitchTo(
            text=Format(text="{deadline_time_text}"),
            id="change_deadline_time",
            state=TasksManagementStates.edit_deadline_time,
        ),
        SwitchTo(
            text=Format(text="{notification_hour_text}"),
            id="change_notification_hour",
            state=TasksManagementStates.edit_hour,
        ),
        Button(
            text=Format(text="{mark_text}"),
            id="mark_task_completed",
            on_click=repository.mark_item,
        ),
        SwitchTo(
            text=Format(text="{back}"),
            id="cancel_task_edition",
            state=TasksManagementStates.view_details,
        ),
        state=TasksManagementStates.edit,
        getter=getters.edit_task,
    ),
    Window(
        Format(text="{item_name}"),
        SwitchTo(
            text=Format("{back}"),
            id="cancel_edit_task_name",
            state=TasksManagementStates.edit,
        ),
        TextInput(
            id="change_task_name",
            type_factory=is_short_text(
                max_length=settings.bot.max_name_length,
            ),
            on_success=repository.change_attr_by_text(attr="name"),
            on_error=on_incorrect_text,
        ),
        getter=edit_name,
        state=TasksManagementStates.edit_name,
    ),
    Window(
        Format(text="{task_description}"),
        SwitchTo(
            text=Format("{back}"),
            id="cancel_edit_description",
            state=TasksManagementStates.edit,
        ),
        TextInput(
            id="change_task_description",
            type_factory=is_short_text(
                max_length=settings.bot.max_description_length,
            ),
            on_success=repository.change_attr_by_text(
                attr="description"
            ),
            on_error=on_incorrect_text,
        ),
        getter=getters.edit_task_description,
        state=TasksManagementStates.edit_description,
    ),
    Window(
        Format(text="{notification_hour_text}"),
        Group(
            Select(
                Format("{item[0]}"),
                id="hour",
                item_id_getter=itemgetter(1),
                items="hours",
                on_click=repository.change_notification_hour,
            ),
            width=2,
        ),
        SwitchTo(
            text=Format("{back}"),
            id="cancel_edit_notification_hour",
            state=TasksManagementStates.edit,
        ),
        getter=getters.edit_task_notification_hour,
        state=TasksManagementStates.edit_hour,
    ),
    Window(
        Format(text="{calendar}"),
        Calendar(
            id="calendar", on_click=repository.change_deadline_date
        ),
        SwitchTo(
            text=Format("{back}"),
            id="cancel_edit_deadline_date",
            state=TasksManagementStates.edit,
        ),
        getter=getters.change_deadline_date,
        state=TasksManagementStates.edit_deadline_date,
    ),
    Window(
        Format(text="{hour_text}"),
        Group(
            Select(
                Format("{item[0]}"),
                id="hour",
                item_id_getter=itemgetter(1),
                items="hours",
                on_click=repository.change_deadline_time,
            ),
            width=2,
        ),
        SwitchTo(
            text=Format("{back}"),
            id="cancel_edit_deadline_time",
            state=TasksManagementStates.edit,
        ),
        getter=getters.change_deadline_time,
        state=TasksManagementStates.edit_deadline_time,
    ),
)
