"""empty message

Revision ID: 0e04d804c3c4
Revises: 6a62ea39671f
Create Date: 2025-07-29 20:19:59.113097

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e04d804c3c4"
down_revision: Union[str, Sequence[str], None] = "6a62ea39671f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("deadline_datetime", sa.DateTime(), nullable=False),
    )
    op.drop_column("tasks", "deadline_time")
    op.drop_column("tasks", "deadline_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "deadline_date",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "deadline_time",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tasks", "deadline_datetime")
    # ### end Alembic commands ###
