"""empty message

Revision ID: e7e1ceccd5bd
Revises: a4f3009e37cd
Create Date: 2025-07-28 22:20:56.698397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7e1ceccd5bd"
down_revision: Union[str, Sequence[str], None] = "a4f3009e37cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracking",
        sa.Column("reminder_date", sa.Date(), nullable=False),
        sa.Column(
            "is_completed",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracking")
    # ### end Alembic commands ###
