"""empty message

Revision ID: 78101cf52937
Revises: 130386fd892e
Create Date: 2025-07-28 21:59:05.476576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78101cf52937"
down_revision: Union[str, Sequence[str], None] = "130386fd892e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "habits",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("purpose", sa.TEXT(), nullable=False),
        sa.Column("notification_hour", sa.Integer(), nullable=False),
        sa.Column(
            "created",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column("date_of_completion", sa.Date(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "notification_hour >= 0 AND notification_hour <= 23",
            name=op.f("ck_habits_ck_notification_hour_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_habits_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habits")),
    )
    op.add_column(
        "tasks", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_tasks_user_id_users"),
        "tasks",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tasks_user_id_users"), "tasks", type_="foreignkey"
    )
    op.drop_column("tasks", "user_id")
    op.drop_table("habits")
    # ### end Alembic commands ###
