"""empty message

Revision ID: 42c1f42e1d29
Revises: 960dad46e266
Create Date: 2025-07-29 13:31:13.525971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42c1f42e1d29"
down_revision: Union[str, Sequence[str], None] = "960dad46e266"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_telegram_id"), "users", ["telegram_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_users_telegram_id"), "users", type_="unique"
    )
    # ### end Alembic commands ###
