"""empty message

Revision ID: 61d84ea40aea
Revises: 19af37632982
Create Date: 2025-07-30 14:07:54.167876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61d84ea40aea"
down_revision: Union[str, Sequence[str], None] = "19af37632982"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_schedules_day_habit_id"),
        "schedules",
        ["day", "habit_id"],
    )
    op.create_unique_constraint(
        op.f("uq_timers_notification_hour_habit_id"),
        "timers",
        ["notification_hour", "habit_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_timers_notification_hour_habit_id"),
        "timers",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_schedules_day_habit_id"),
        "schedules",
        type_="unique",
    )
    # ### end Alembic commands ###
