"""empty message

Revision ID: 77f46764f899
Revises: 31f99f2e9d0a
Create Date: 2025-07-28 21:41:36.299830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77f46764f899"
down_revision: Union[str, Sequence[str], None] = "31f99f2e9d0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("deadline_date", sa.Date(), nullable=False),
        sa.Column("deadline_time", sa.Integer(), nullable=False),
        sa.Column(
            "hour_before_reminder", sa.Integer(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "deadline_time >= 0 AND deadline_time <= 23",
            name=op.f("ck_tasks_ck_time_range"),
        ),
        sa.CheckConstraint(
            "hour_before_reminder >= 1 AND hour_before_reminder <= 23",
            name=op.f("ck_tasks_ck_reminder_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
