"""empty message

Revision ID: 130386fd892e
Revises: 77f46764f899
Create Date: 2025-07-28 21:44:03.570861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "130386fd892e"
down_revision: Union[str, Sequence[str], None] = "77f46764f899"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("date_of_completion", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "date_of_completion")
    # ### end Alembic commands ###
