"""empty message

Revision ID: a4f3009e37cd
Revises: 56ebc448ca68
Create Date: 2025-07-28 22:14:32.749875

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4f3009e37cd"
down_revision: Union[str, Sequence[str], None] = "56ebc448ca68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timers",
        sa.Column("notification_hour", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "notification_hour >= 0 AND notification_hour <= 23",
            name=op.f("ck_timers_ck_notification_hour_range"),
        ),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
            name=op.f("fk_timers_habit_id_habits"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timers")),
    )
    op.drop_column("habits", "notification_hour")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "habits",
        sa.Column(
            "notification_hour",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("timers")
    # ### end Alembic commands ###
