"""empty message

Revision ID: 493dc00199cb
Revises: 61d84ea40aea
Create Date: 2025-08-04 16:06:29.066836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "493dc00199cb"
down_revision: Union[str, Sequence[str], None] = "61d84ea40aea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("habits", "created")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "habits",
        sa.Column(
            "created",
            sa.DATE(),
            server_default=sa.text("CURRENT_DATE"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
