"""empty message

Revision ID: 960dad46e266
Revises: e7e1ceccd5bd
Create Date: 2025-07-29 13:19:24.468248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "960dad46e266"
down_revision: Union[str, Sequence[str], None] = "e7e1ceccd5bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
