"""empty message

Revision ID: 31f99f2e9d0a
Revises: a57fd1575bd3
Create Date: 2025-07-28 20:41:21.020206

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31f99f2e9d0a"
down_revision: Union[str, Sequence[str], None] = "a57fd1575bd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_users_username"), "users", type_="unique"
    )
    # ### end Alembic commands ###
