"""empty message

Revision ID: e082d59a6fa0
Revises: 6fda11c66f54
Create Date: 2025-07-31 13:29:54.614919

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e082d59a6fa0"
down_revision: Union[str, Sequence[str], None] = "6fda11c66f54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "language",
            sa.Enum("ru", "en", name="languages"),
            server_default="ru",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language")
    # ### end Alembic commands ###
