services:
  redis:
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
    volumes:
      - ./rabbitmq_data:/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 3s
      retries: 3