services:
  redis:
    image: redis:7.4-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3