name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.8-alpine3.18
        env:
          POSTGRES_USER: postgres_test
          POSTGRES_PASSWORD: postgres_test
          POSTGRES_DB: postgres_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: postgres_test
      admin_login: admin
      admin_password: admin
      admin_telegram_id: 123
      PYTHONPATH: ${{ github.workspace }}/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd backend
          poetry install

      - name: Run tests
        run: |
          cd backend
          python create_certs.py
          poetry run pytest --maxfail=2 --disable-warnings -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Timeweb via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TIMEWEB_HOST }}
          username: ${{ secrets.TIMEWEB_USER }}
          key: ${{ secrets.TIMEWEB_KEY }}
          script: |
            cd /root/time-management
            docker compose down
            git pull
            docker compose up -d --build
